services:
  postgres:
    image: postgres:16
    container_name: shameleon-postgres
    environment:
      POSTGRES_DB: shameleon
      POSTGRES_USER: shameleon
      POSTGRES_PASSWORD: shameleon
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: